spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:


  jpa:
    # 스키마를 생성하고 어플리케이션이 종료시 삭제
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 402641556061-ansf2v8fmnqb3udf1o83b63igvbkllrj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 584030913270431
            client-secret: af4e5946ce1161da7526d49acf11ed0e
            scope:
              - email
              - public_profile



logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    boardexample:
      myboard: info
