Create Table Board(
 id bigint generated by default as identity,
 title varchar(255),
 content varchar(255),
 writer varchar(255),
 hits integer,
 isDeleted boolean,
 lastModifiedDate date,
 createDate  date,
 primary key (id)
)


Create Table Member2(
 id bigint generated by default as identity,
 username varchar(255),
 password varchar(255),
 name varchar(255),
 email varchar(255),
 role varchar(255),
 isDeleted boolean,
 lastModifiedDate date,
 createDate date,
 primary key (id)

)