Create Table Board(
 id bigint generated by default as identity,
 title varchar(255),
 content varchar(255),
 writer varchar(255),
 hits integer,
 isDeleted boolean,
 lastModifiedDate date,
 createDate BOARD date,
 primary key (id)
)